# Generated by Django 6.0.5 on 2026-06-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agent_productionagent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionAgent',
        ),
    ]
