# Generated by Django 5.1.15 on 2026-06-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_productionagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('superviseur', 'Responsable Technique'), ('finance', 'Responsable Finanaciere')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
