# Generated by Django 6.0.5 on 2026-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_categorie_alter_operation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('', 'Sélectionner un type'), ('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=20),
        ),
    ]
