# Generated by Django 5.2.7 on 2026-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_operation_operation_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['operation_type'], name='finance_ope_operati_e6dca5_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['operation_date'], name='finance_ope_operati_44a75d_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['categorie'], name='finance_ope_categor_bef3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['operation_type', 'operation_date'], name='finance_ope_operati_d7111a_idx'),
        ),
    ]
