# Generated by Django 6.0.5 on 2026-05-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_operation_finance_ope_operati_e6dca5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contenant', models.CharField(blank=True, max_length=100)),
                ('quantite_initiale', models.PositiveIntegerField(default=0)),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('quantite_perdue', models.PositiveIntegerField(default=0)),
                ('quantite_offerte', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='usage_type',
            field=models.CharField(choices=[('depense', 'Dépense'), ('stock', 'Stock'), ('both', 'Les deux')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('', 'Sélectionner un type'), ('revenu', 'Revenu'), ('depense', 'Dépense'), ('stock', 'Stock')], max_length=20),
        ),
    ]
