# Generated by Django 6.0.5 on 2026-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_produit_categorie_usage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='usage_type',
            field=models.CharField(choices=[('depense', 'Dépense'), ('revenu', 'Revenu'), ('stock', 'Stock'), ('both', 'Les deux')], default='both', max_length=20),
        ),
    ]
