# Generated by Django 6.0.5 on 2026-05-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_categorie_usage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='contenant',
        ),
        migrations.AddField(
            model_name='produit',
            name='operation_stock',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='finance.operation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=150),
        ),
    ]
