# Generated by Django 6.0.5 on 2026-05-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_produit_contenant_produit_operation_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
