# Generated by Django 6.0.5 on 2026-06-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_produit_note'),
        ('users', '0003_delete_productionagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_attachee', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='users.agent')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='finance.produit')),
            ],
        ),
    ]
