# Generated by Django 6.0.6 on 2026-06-22 00:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_productionagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_ajuster', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant (+/-) ajouté au solde calculé. Solde exposé = revenus - dépenses + ajustement.', max_digits=14, verbose_name='Ajustement du solde')),
                ('note', models.TextField(blank=True, help_text="Raison / justification de l'ajustement.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre financier',
                'verbose_name_plural': 'Paramètres financiers',
            },
        ),
    ]
