# Generated by Django 6.0.6 on 2026-06-21 23:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('unite_rendement', models.CharField(default='t', help_text='Unité du rendement (t, kg, ...)', max_length=10)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex. : Demi hectare - 4 cultures', max_length=255)),
                ('saison', models.CharField(blank=True, help_text='Ex. : Hivernage 2026', max_length=100)),
                ('superficie_ha', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=8, verbose_name='Superficie (ha)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis à la direction'), ('valide', 'Validé'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='soumis', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_culture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_demande', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BesoinCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semence_quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('semence_unite', models.CharField(default='kg', help_text='kg, g, ...', max_length=10)),
                ('engrais', models.TextField(blank=True, help_text='Ex. : 2 Sac NPK et 1 Sac Urée')),
                ('produit_phyto', models.TextField(blank=True, help_text='Ex. : Herbicide sélectif 1L, Insecticide Dimétho 1L', verbose_name='Produits phytosanitaires')),
                ('rendement_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendement estimé')),
                ('rendement_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendement réel')),
                ('date_recolte', models.DateField(blank=True, null=True)),
                ('observation_direction', models.TextField(blank=True, verbose_name='Observation de la direction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besoins', to='cultures.culture')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='cultures.demandeculture')),
            ],
            options={
                'ordering': ['culture__nom'],
            },
        ),
    ]
