# Generated by Django 5.1.15 on 2026-06-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0003_refactor_fiche_culture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficheculture',
            options={'ordering': ['-date_debut', '-created_at']},
        ),
        migrations.AlterField(
            model_name='besoinculture',
            name='semence_unite',
            field=models.CharField(default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='ficheculture',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_culture', to=settings.AUTH_USER_MODEL),
        ),
    ]
