# Generated by Django 5.1.15 on 2026-06-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0004_alter_ficheculture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoinculture',
            name='recolte_cloturee',
            field=models.BooleanField(default=False, help_text='Marqué vrai quand le technicien signale la fin de la récolte.', verbose_name='Récolte clôturée'),
        ),
        migrations.AlterField(
            model_name='besoinculture',
            name='date_recolte',
            field=models.DateField(blank=True, null=True, verbose_name='Date de clôture récolte'),
        ),
        migrations.CreateModel(
            name='PassageRecolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passage', models.DateField(verbose_name='Date du passage')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité récoltée')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_recolte', to='cultures.besoinculture')),
            ],
            options={
                'ordering': ['date_passage'],
            },
        ),
    ]
