# Generated by Django 5.1.15 on 2026-06-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0005_besoinculture_recolte_cloturee_and_more'),
        ('users', '0004_user_type_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilan_activites', models.TextField(blank=True, verbose_name='Bilan des activités')),
                ('problemes', models.TextField(blank=True, verbose_name='Difficultés rencontrées')),
                ('solutions', models.TextField(blank=True, verbose_name='Solutions appliquées')),
                ('resultats', models.TextField(blank=True, verbose_name='Résultats obtenus')),
                ('perspectives', models.TextField(blank=True, verbose_name='Perspectives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('besoin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport_culture', to='cultures.besoinculture', verbose_name='Culture concernée')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implication', models.PositiveSmallIntegerField(choices=[(1, '1 - Faible'), (2, '2 - Moyenne'), (3, '3 - Bonne'), (4, '4 - Très bonne'), (5, '5 - Excellente')], default=3, verbose_name="Niveau d'implication")),
                ('maitrise', models.PositiveSmallIntegerField(choices=[(1, '1 - Débutant'), (2, '2 - En apprentissage'), (3, '3 - Autonome'), (4, '4 - Bonne maîtrise'), (5, '5 - Expert')], default=3, verbose_name='Maîtrise de la culture')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_culture', to='users.agent')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='cultures.rapportculture')),
            ],
            options={
                'unique_together': {('rapport', 'agent')},
            },
        ),
    ]
