# Generated by Django 5.1.15 on 2026-08-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit agricole',
                'verbose_name_plural': 'Produits agricoles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Cession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_cession', models.DecimalField(decimal_places=2, help_text='Prix total convenu pour cette cession (pas un prix unitaire).', max_digits=12)),
                ('date_cession', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cessions', to='cessions.produitagricole')),
            ],
            options={
                'verbose_name': 'Cession',
                'verbose_name_plural': 'Cessions',
                'ordering': ['-date_cession', '-created_at'],
                'indexes': [models.Index(fields=['date_cession'], name='cessions_ce_date_ce_c226b0_idx'), models.Index(fields=['produit'], name='cessions_ce_produit_e958ad_idx')],
            },
        ),
    ]
