# Generated by Django 5.1.15 on 2026-08-14 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cession',
            name='derniere_erreur',
            field=models.TextField(blank=True, help_text='Message de la dernière erreur de transmission, le cas échéant.'),
        ),
        migrations.AddField(
            model_name='cession',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='cession',
            name='statut',
            field=models.CharField(choices=[('locale', 'Créée localement'), ('transmise', 'Transmise à DAMS Distribution'), ('echec', 'Échec de transmission')], default='locale', max_length=20),
        ),
        migrations.AddField(
            model_name='cession',
            name='transmise_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cession',
            name='prix_cession',
            field=models.DecimalField(decimal_places=2, help_text='Prix unitaire de cession (par unité de quantité, pas un montant total).', max_digits=12),
        ),
    ]
