# Generated by Django 5.1.15 on 2026-06-08 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_delete_productionagent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activite_realisee', models.TextField()),
                ('difficulte', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implication', models.PositiveSmallIntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Bonne'), (4, 'Très bonne'), (5, 'Excellente')], default=3)),
                ('maitrise', models.PositiveSmallIntegerField(choices=[(1, 'Débutant'), (2, 'En apprentissage'), (3, 'Autonome'), (4, 'Bonne maîtrise'), (5, 'Expert')], default=3)),
                ('observation', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='users.agent')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rapports.rapportjournalier')),
            ],
            options={
                'unique_together': {('rapport', 'agent')},
            },
        ),
    ]
