# Generated by Django 5.1.15 on 2026-06-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapportjournalier',
            old_name='difficulte',
            new_name='probleme',
        ),
    ]
