# Generated by Django 5.1.15 on 2026-06-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0002_rename_difficulte_rapportjournalier_probleme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapportjournalier',
            old_name='commentaire',
            new_name='resultat_obtenu',
        ),
    ]
