# Generated by Django 6.0.6 on 2026-06-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0003_rename_commentaire_rapportjournalier_resultat_obtenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationagent',
            name='implication',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Faible'), (2, '2 - Moyenne'), (3, '3 - Bonne'), (4, '4 - Très bonne'), (5, '5 - Excellente')], default=3),
        ),
        migrations.AlterField(
            model_name='participationagent',
            name='maitrise',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Débutant'), (2, '2 - En apprentissage'), (3, '3 - Autonome'), (4, '4 - Bonne maîtrise'), (5, '5 - Expert')], default=3),
        ),
    ]
