# Generated by Django 5.1.15 on 2026-08-05 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0010_parametrefinancier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('avance_tresorerie', 'Avance de trésorerie'), ('depense_compte', 'Dépense pour le compte du champ')], max_length=30)),
                ('reference_superviseur', models.CharField(help_text='Identifiant ou nom du superviseur côté DAMS Distribution.', max_length=150)),
                ('reference_externe', models.CharField(blank=True, help_text="Référence de l'engagement côté DAMS Distribution.", max_length=100)),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.CharField(max_length=255)),
                ('date_engagement', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_generee', models.ForeignKey(blank=True, help_text='Operation revenu créée automatiquement (avance de trésorerie uniquement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_origine', to='finance.operation')),
                ('technicien', models.ForeignKey(blank=True, help_text='Technicien dams_agro concerné, si connu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement financier',
                'verbose_name_plural': 'Engagements financiers',
                'ordering': ['-date_engagement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_remboursement', models.DateField()),
                ('reference_externe', models.CharField(blank=True, help_text='Référence du remboursement côté DAMS Distribution.', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='engagements.engagementfinancier')),
                ('operation_generee', models.ForeignKey(blank=True, help_text='Operation dépense créée automatiquement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursement_origine', to='finance.operation')),
            ],
            options={
                'verbose_name': "Remboursement d'engagement",
                'verbose_name_plural': "Remboursements d'engagements",
                'ordering': ['-date_remboursement', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='engagementfinancier',
            index=models.Index(fields=['nature'], name='engagements_nature_683fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementfinancier',
            index=models.Index(fields=['date_engagement'], name='engagements_date_en_b3c2d1_idx'),
        ),
    ]
